### PR TITLE
Fix: rust examples

### PR DESCRIPTION
**Pull request by thesimplekid**

### CODE REVIEW

**Comment by cdecker** [comment]
Hi @thesimplekid, thanks for opening this PR, as you can tell the docs are lagging a bit behind the implementation, so all help is very much appreciated :hugs:

**Comment by cdecker** [comment]
> Hey, no problem. I don't have an invite code to test but these compile so, I'll open the pr.

Would you like one or two, as a thank you?

**Comment by thesimplekid** [comment]
> Would you like one or two, as a thank you?

That would be great if you don't mind.

**Comment by cdecker** [comment]
Not sure if I can send you a DM on GH, but feel free to reach out to me on TG (@cdecker) or Nost (npub1j08dgz2j85em48y6hxn226kj5c38e84fykuvxu7tac8l4f07e4mqkspdm2), and I'll get some invites to you asap :-)

**Comment by thesimplekid** [comment]
Thank you just sent nostr dm.

**Pull request merged**
