### PR TITLE
cli: Document pairing process

### PR DESCRIPTION
**Pull request by nepet**
This PR adds some basic documentation about how to use the pairing process.

### CODE REVIEW

**Comment by nepet** [comment]
Is based on #515

**Comment by nepet** [comment]
@Randy808 I changed the dir structure of the examples quite a bit, please check If you are OK with how it works now.

**Comment by cdecker** [comment]
Looking good :+1: I'll wait for @Randy808 to ACK the change in paths and merge asap ^^

**Review by Randy808 — APPROVED** [review]
Looks good!

**Pull request merged**
