### PR TITLE
docs: Add a section on providing certs at runtime

### PR DESCRIPTION
**Pull request by cdecker**
Erik pointed out that providing the certificate at compile-time might be sub-optimal, as it does not apply to precompiled bindings.

Suggested-by: @ErikDeSmedt

### CODE REVIEW

**Comment by ErikDeSmedt** [comment]
I've changed the docs to reflect what the filenames are that are returned by the developer console.

It is unclear why we are reverting this.

For all other things. ACK

Major improvement

**Comment by cdecker** [comment]
Sorry @ErikDeSmedt one of my lints removed trailing whitespace apparently, marking the line as changed, and I didn't check carefully enough. I'll update this and republish without reverting your name changes.

**Comment by cdecker** [comment]
Should be fixed now @ErikDeSmedt

**Comment by ErikDeSmedt** [comment]
Approve, this one is good to go

**Review by ErikDeSmedt — APPROVED** [review]
Approved, these changes are good to be merged.

**Comment by cdecker** [comment]
Thanks @ErikDeSmedt

**Pull request merged**
